version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres/service
      REDIS_URL: redis://redis:6379/0
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"

  celery_worker:
    build: .
    depends_on:
      - backend
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres/service
      REDIS_URL: redis://redis:6379/0
    command: celery -A app.workers.celery_app worker --loglevel=info

